<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Library.aspx.cs" Inherits="WebApplication2.Library" %>
<asp:Content ID="Library" ContentPlaceHolderID="MainContent" runat="server">
    
    <div align="center" class="jumbotron">
        <h1>My Library</h1>
    </div>



    <asp:GridView ID="GridView1" runat="server" HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="Id" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2">
        <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
<HeaderStyle VerticalAlign="Middle" BackColor="#A55129" Font-Bold="True" ForeColor="White"></HeaderStyle>
        <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#FFF1D4" />
        <SortedAscendingHeaderStyle BackColor="#B95C30" />
        <SortedDescendingCellStyle BackColor="#F1E5CE" />
        <SortedDescendingHeaderStyle BackColor="#93451F" />
    </asp:GridView>
  



</asp:Content>
